/*
gen_dec4.c - generator for the SWAR base64 decode tables.

Emits four 32-bit lookup tables used by the scalar decoder's clean-quad
bulk path. Each base64 char maps to its 6-bit value pre-shifted into the
correct position of a 24-bit output word; every non-alphabet byte (padding
and whitespace included) carries a sentinel high bit so an OR of a quad
reveals invalidity via bit 24.

Build/run: cc tools/gen_dec4.c -o gen_dec4 && ./gen_dec4 > src/cdecode_swar_table.h
*/

#include <stdio.h>
#include <stdint.h>

/* Sentinel set in every invalid entry; bit 24 is clear for all valid
   quads since the largest valid contribution is 63 << 18 (bit 23). */
#define SENT 0x01000000u

/* base64 char -> 0..63, or -1 for any non-alphabet byte. */
static int value_of(int c)
{
	if (c >= 'A' && c <= 'Z') return c - 'A';
	if (c >= 'a' && c <= 'z') return c - 'a' + 26;
	if (c >= '0' && c <= '9') return c - '0' + 52;
	if (c == '+') return 62;
	if (c == '/') return 63;
	return -1;
}

static void emit(const char* name, int shift)
{
	int i;
	printf("static const uint32_t %s[256] = {", name);
	for (i = 0; i < 256; ++i)
	{
		int v = value_of(i);
		uint32_t e = (v < 0) ? SENT : ((uint32_t)v << shift);
		if (i % 5 == 0)
			printf("\n\t");
		printf("0x%08lxu,", (unsigned long)e);
	}
	printf("\n};\n");
}

int main(void)
{
	printf("/*\n");
	printf("Generated by tools/gen_dec4.c - do not edit by hand.\n");
	printf("Regenerate: cc tools/gen_dec4.c -o gen_dec4 && "
	       "./gen_dec4 > src/cdecode_swar_table.h\n");
	printf("*/\n\n");
	printf("#include <stdint.h>\n\n");
	emit("b64_dec0", 18);
	printf("\n");
	emit("b64_dec1", 12);
	printf("\n");
	emit("b64_dec2", 6);
	printf("\n");
	emit("b64_dec3", 0);
	return 0;
}
