/*
gen_enc12.c - generator for the 12-bit dual-char base64 encode table.

Generated by tools/gen_enc12.c - do not edit by hand. Regenerate:
  cc tools/gen_enc12.c -o gen_enc12 && ./gen_enc12 > src/cencode12_table.h

This is part of the libb64 project, and has been placed in the public domain.
For details, see http://sourceforge.net/projects/libb64
*/

#include <stdio.h>

static const char encoding[] =
	"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

int main(void)
{
	int i;

	printf(
"/*\n"
"cencode12_table.h - 12-bit dual-char base64 encode lookup table.\n"
"\n"
"Generated by tools/gen_enc12.c - do not edit by hand. Regenerate:\n"
"  cc tools/gen_enc12.c -o gen_enc12 && ./gen_enc12 > src/cencode12_table.h\n"
"\n"
"For a 12-bit index i, the two output chars are encoding[i >> 6] (high\n"
"six bits) and encoding[i & 0x3f] (low six bits). Packing order: low\n"
"byte = encoding[i >> 6], high byte = encoding[i & 0x3f], so the two\n"
"chars are emitted in order via *p++ = t & 0xff; *p++ = t >> 8;\n"
"*/\n"
"\n"
"#ifndef B64_CENCODE12_TABLE_H\n"
"#define B64_CENCODE12_TABLE_H\n"
"\n"
"#include <stdint.h>\n"
"\n"
"static const uint16_t base64_enc12[4096] = {\n");

	for (i = 0; i < 4096; ++i)
	{
		unsigned c_hi = (unsigned char)encoding[i >> 6];
		unsigned c_lo = (unsigned char)encoding[i & 0x3f];
		unsigned packed = c_hi | (c_lo << 8);

		if (i % 8 == 0)
			printf("\t");
		printf("0x%04x,", packed);
		if (i % 8 == 7)
			printf("\n");
		else
			printf(" ");
	}

	printf("};\n\n#endif /* B64_CENCODE12_TABLE_H */\n");
	return 0;
}
